version: '3'

services:
  delay-server:
    container_name: my-site
    image: qdw/my-site
    ports:
      - "8080:8089"
    volumes:
      - "./tmp:/tmp"
    environment:
      SPRING_DATASOURCE_DRUID_URL: jdbc:mysql://172.17.0.1:3306/lu_tale?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
      SPRING_DATASOURCE_DRUID_USERNAME: root
      SPRING_DATASOURCE_DRUID_PASSWORD: 123321
      QINIU_ACCESSKEY: ""
      QINIU_SERECTKEY: ""
      QINIU_BUCKET: ""
      QINIU_CDN_URL: ""